#!/bin/bash

args=":cf"

BRANCH=$(git symbolic-ref --short HEAD)

synch_remote(){
    echo ">> Synch repo"
    git fetch
    git pull

}


while getopts ${args} opt; do
    case ${opt} in
        c) 
            echo ">> The '$2' comment has been set."
            synch_remote
            git add .
            git commit -m $2
            git push origin $BRANCH
            ;;
        f)
            echo ">> The '$3' comment has been set."
            synch_remote
            git add $2
            git commit -m $3
            git push origin $BRANCH
            ;;
        ?)
            echo "Invalid option: -${OPTARG}."
            exit 1
            ;;
    esac
done
