#!/bin/bash

args=":cf"
#current branch
BRANCH=$(git symbolic-ref --short HEAD)
#pull remote data
synch_remote(){
    echo ">> Synch repo"
    git fetch
    git pull

}
#switch case - push changes.
while getopts ${args} opt; do
    case ${opt} in
        c) 
            synch_remote
            git add .
            git commit -m $1
            git push origin $BRANCH
            ;;
        f)
            synch_remote
            git add $1
            git commit -m $2
            git push origin $BRANCH
            ;;
        ?)
            echo "Invalid option: -${OPTARG}."
            exit 1
            ;;
    esac
done
